import streamlit as st
st.title('Model: UNet')
st.header('Dataset: 3500 train | 1000 valid | 500 test')
st.subheader('Training history on 20 epochs')
col1, col2, col3 = st.columns(3)
col1.image('images/loss_unet.png', caption="LOSS")
col3.image('images/acc_Unet.png', caption="ACCURACY")
col2.image('images/IoU_Unet.png', 'IoU')
st.subheader('Test loss: 0.545 | Test IoU: 0.74 | Test accuracy: 0.82')
st.subheader('Time of training: 32 minutes')